---
abstract: 'Template metaprogramming with Moose'
author:
  - 'Robert Krimen, C<< <rkrimen at cpan.org> >>'
build_requires:
  Test::Most: 0
distribution_type: module
generated_by: 'Module::Install version 0.760'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MooseX-Scaffold
no_index:
  directory:
    - inc
    - t
requires:
  Carp::Clan: 0
  Class::Inspector: 0
  Moose: 0.580
  MooseX::ClassAttribute: 0.060
resources:
  license: http://dev.perl.org/licenses/
  repository: http://github.com/robertkrimen/moosex-scaffold/tree/master
version: 0.02
